Arrange and create a matrix

In [3]:
import numpy as np

In [14]:
np.random.normal(5,5,(5,5))


array([[ 7.35806994,  2.23286818, -4.7064047 ,  1.86890317,  8.02175772],
       [ 9.95053307,  8.19174916, -2.45951451,  2.3379915 , 10.45206518],
       [ 4.31412192,  2.54600394,  3.60772813,  1.27084886,  2.80140866],
       [ 7.8307906 ,  3.70518577,  2.57216328,  3.33663168,  5.19211887],
       [-2.05188652,  4.30417353, 10.14607536,  1.46521154,  6.86584345]])

In [18]:
np.arange(0,5,2)

array([0, 2, 4])

In [40]:
x = np.random.randint(0,5,(5,5))

x[:4,2:]

array([[0, 1, 3],
       [3, 0, 2],
       [1, 2, 0],
       [4, 0, 1]])

In [23]:
np.random.rand(5,5)

array([[0.32739393, 0.54788385, 0.05646445, 0.45092935, 0.85125525],
       [0.97367189, 0.48374605, 0.38820646, 0.74001949, 0.51976516],
       [0.78256745, 0.73500416, 0.78303602, 0.1942761 , 0.0920196 ],
       [0.70799223, 0.69727864, 0.95390336, 0.56830842, 0.58962401],
       [0.34721998, 0.84035909, 0.61629079, 0.25712007, 0.47996798]])

In [52]:
y = np.random.randint(0,20,(3,3))
type(y)

numpy.ndarray

In [53]:
x = np.array(np.random.randint(0,20,(3,3)))
print(x)

[[ 7 12  0]
 [15  5  9]
 [12  4 14]]


In [47]:
z = x+y

In [48]:
z.size

9

In [62]:
hallo = x*y
hallo

array([[ 77,  60,   0],
       [240,   5,  54],
       [132,   4,   0]])

In [63]:
import pandas as pd

meow = pd.DataFrame(hallo)
print(meow)

     0   1   2
0   77  60   0
1  240   5  54
2  132   4   0


In [64]:
students = [{"name":"Alice","course":"BSME","strand":"STEM"},
            {"name":"Bob","course":"BSME","strand":"HUMSS"},
            {"name":"Carol","course":"BSITE","strand":"ABM"},
            {"name":"Charlie","course":"BSITE","strand":"ABM"},
            {"name":"Chuck","course":"BSLM","strand":"ABM"},
            {"name":"Charlie","course":"BSME","strand":"ABM"},
            {"name":"Dave","course":"BSMGTH","strand":"GAS"},
            {"name":"Eve","course":"BSMGT","strand":"HUMSS"},
            {"name":"Frank","course":"BSITE","strand":"Arts and Design", "bondage":"shibari"},
            ]



In [68]:
meow = pd.DataFrame(students)
meow["name"]

0      Alice
1        Bob
2      Carol
3    Charlie
4      Chuck
5    Charlie
6       Dave
7        Eve
8      Frank
Name: name, dtype: object